/**
 * WordPress Astro.js Integration
 *
 * Astro-specific WordPress integration with live loaders, static loaders,
 * server actions, auth bridge helpers, catalog integration, and components.
 */

export type {
  AbilityActionOptions,
  ActionClientResolver,
  ActionResponseMapper,
  CreatePostActionConfig,
  CreatePostActionOptions,
  CreatePostInput,
  CreateTermActionConfig,
  CreateTermActionOptions,
  CreateTermInput,
  CreateUserActionConfig,
  CreateUserActionOptions,
  CreateUserInput,
  DeleteAbilityActionConfig,
  DeletePostActionConfig,
  DeletePostActionOptions,
  DeletePostInput,
  DeletePostResult,
  DeleteTermActionConfig,
  DeleteTermActionOptions,
  DeleteTermInput,
  DeleteTermResult,
  DeleteUserActionConfig,
  DeleteUserActionOptions,
  DeleteUserInput,
  DeleteUserResult,
  ExecuteAbilityOptions,
  ExecuteCreateConfig,
  ExecuteCreateOptions,
  ExecuteCreateTermConfig,
  ExecuteCreateTermOptions,
  ExecuteCreateUserConfig,
  ExecuteCreateUserOptions,
  ExecuteDeleteAbilityConfig,
  ExecuteDeleteAbilityOptions,
  ExecuteDeleteConfig,
  ExecuteDeleteOptions,
  ExecuteDeleteTermConfig,
  ExecuteDeleteTermOptions,
  ExecuteDeleteUserConfig,
  ExecuteDeleteUserOptions,
  ExecuteGetAbilityConfig,
  ExecuteGetAbilityOptions,
  ExecuteRunAbilityConfig,
  ExecuteRunAbilityOptions,
  ExecuteUpdateConfig,
  ExecuteUpdateOptions,
  ExecuteUpdateTermConfig,
  ExecuteUpdateTermOptions,
  ExecuteUpdateUserConfig,
  ExecuteUpdateUserOptions,
  GetAbilityActionConfig,
  ResolvableActionClient,
  RunAbilityActionConfig,
  UpdatePostActionConfig,
  UpdatePostActionOptions,
  UpdatePostInput,
  UpdateTermActionConfig,
  UpdateTermActionOptions,
  UpdateTermInput,
  UpdateUserActionConfig,
  UpdateUserActionOptions,
  UpdateUserInput,
  WpCacheInvalidateInput,
} from './actions';
// Export predefined server actions
export {
  createCreatePostAction,
  createCreateTermAction,
  createCreateUserAction,
  createDeleteAbilityAction,
  createDeletePostAction,
  createDeleteTermAction,
  createDeleteUserAction,
  createGetAbilityAction,
  createPostInputSchema,
  createRunAbilityAction,
  createTermInputSchema,
  createUpdatePostAction,
  createUpdateTermAction,
  createUpdateUserAction,
  createUserInputSchema,
  createWpCacheInvalidateAction,
  deleteAbilityInputSchema,
  deletePostInputSchema,
  deleteTermInputSchema,
  deleteUserInputSchema,
  getAbilityInputSchema,
  runAbilityInputSchema,
  updatePostInputSchema,
  updateTermInputSchema,
  updateUserInputSchema,
  wpCacheInvalidateInputSchema,
} from './actions';
export type {
  CategoryFilter,
  ContentFilter,
  MediaFilter,
  PageFilter,
  PostFilter,
  TagFilter,
  TermFilter,
  UserFilter,
  WordPressContentLoaderOptions,
  WordPressContentStaticLoaderOptions,
  WordPressEmbedMode,
  WordPressEntryMappingOptions,
  WordPressLiveContentLoaderOptions,
  WordPressLoaderEntryMapper,
  WordPressTermLoaderOptions,
  WordPressTermStaticLoaderOptions,
} from './loaders';
// Export live loaders (for defineLiveCollection - runtime fetching)
// Export static loaders (for defineCollection - build-time only)
export {
  wordPressCategoryLoader,
  wordPressCategoryStaticLoader,
  wordPressContentLoader,
  wordPressContentStaticLoader,
  wordPressMediaLoader,
  wordPressMediaStaticLoader,
  wordPressPageLoader,
  wordPressPageStaticLoader,
  wordPressPostLoader,
  wordPressPostStaticLoader,
  wordPressTagLoader,
  wordPressTagStaticLoader,
  wordPressTermLoader,
  wordPressTermStaticLoader,
  wordPressUserLoader,
  wordPressUserStaticLoader,
} from './loaders';
export type {
  WordPressAuthBridge,
  WordPressAuthBridgeConfig,
  WordPressAuthSession,
  WordPressLoginAction,
  WordPressLoginActionPayload,
  WordPressLoginActionResult,
  WordPressLoginInput,
} from './server';
// Export server auth bridge helpers
export {
  createWordPressAuthBridge,
  wordPressLoginInputSchema,
} from './server';

// Components are imported directly via:
// import WPImage from 'wp-astrojs-integration/components/WPImage.astro';
// import WPContent from 'wp-astrojs-integration/components/WPContent.astro';
