/**
 * WordPress Astro.js Integration
 *
 * Fast and better WordPress integration for Astro.js with live loaders,
 * static loaders, client API, and full Gutenberg block support.
 */

export type {
  BasicAuthCredentials,
  CategoriesFilter,
  CommentsFilter,
  CommentsResourceClient,
  ContentResourceClient,
  CookieNonceAuthCredentials,
  DeleteAbilityInput,
  DeleteOptions,
  FetchResult,
  GetAbilityInput,
  HeaderAuthCredentials,
  JwtAuthCredentials,
  JwtAuthTokenResponse,
  JwtAuthValidationResponse,
  JwtLoginCredentials,
  MediaFilter as ClientMediaFilter,
  MediaResourceClient,
  PagesFilter,
  PaginatedResponse,
  PaginationParams,
  PostsFilter,
  QueryParams,
  RequestAuthResolver,
  ResolvableWordPressAuth,
  RunAbilityInput,
  SettingsResourceClient,
  TagsFilter,
  TermsResourceClient,
  TermWriteInput,
  UserDeleteOptions,
  UsersFilter,
  UsersResourceClient,
  UserWriteInput,
  WordPressAbility,
  WordPressAbilityAnnotations,
  WordPressAbilityCategory,
  WordPressAbilityDescription,
  WordPressAbilityRuntime,
  WordPressAbilitySchemaSet,
  WordPressAuthConfig,
  WordPressAuthHeaders,
  WordPressAuthHeadersProvider,
  WordPressAuthInput,
  WordPressAuthor,
  WordPressAuthorizationInput,
  WordPressAuthRequest,
  WordPressAuthResolver,
  WordPressBase,
  WordPressCategory,
  WordPressClientConfig,
  WordPressComment,
  WordPressContent,
  WordPressDeleteResult,
  // Discovery types
  WordPressDiscoveryCatalog,
  WordPressDiscoveryOptions,
  WordPressDiscoveryWarning,
  WordPressEmbeddedMedia,
  WordPressError,
  WordPressJsonSchema,
  WordPressMedia,
  WordPressMediaUploadInput,
  WordPressPage,
  WordPressPost,
  WordPressPostWriteBase,
  WordPressPostWriteFields,
  WordPressRequestOptions,
  WordPressRequestOverrides,
  WordPressRequestResult,
  WordPressResourceCapabilities,
  WordPressResourceDescription,
  WordPressResourceSchemaSet,
  WordPressSchemaIssue,
  WordPressSettings,
  WordPressStandardSchema,
  WordPressTag,
  WordPressWritePayload,
} from 'fluent-wp-client';
// Export runtime-agnostic standalone client
// Export auth utilities
export {
  createAuthResolver,
  createBasicAuthHeader,
  createJwtAuthHeader,
  createWordPressAuthHeader,
  isStandardSchema,
  resolveWordPressAuth,
  resolveWordPressRequestCredentials,
  resolveWordPressRequestHeaders,
  WordPressAbilityBuilder,
  WordPressClient,
} from 'fluent-wp-client';

export type {
  AbilityZodSchemas,
  ResourceZodSchemas,
} from 'fluent-wp-client/zod';
// Export schemas and core WP types from standalone client package
// Export embed extraction helpers
// Export schema discovery helpers
export {
  ACF_POSTS_EMBED_KEY,
  ACF_TERMS_EMBED_KEY,
  abilityAnnotationsSchema,
  abilityCategorySchema,
  abilitySchema,
  authorSchema,
  baseWordPressSchema,
  categorySchema,
  commentSchema,
  contentWordPressSchema,
  embeddedMediaSchema,
  getAcfEmbeddedPosts,
  getAcfEmbeddedTerms,
  getAcfFieldId,
  getAcfFieldIds,
  getAcfFieldPost,
  getAcfFieldPosts,
  getAcfFieldTerms,
  getEmbeddableLinkKeys,
  getEmbeddedAuthor,
  getEmbeddedData,
  getEmbeddedFeaturedMedia,
  getEmbeddedParent,
  getEmbeddedReplies,
  getEmbeddedTerms,
  getLinkEntries,
  jwtAuthErrorResponseSchema,
  jwtAuthTokenResponseSchema,
  jwtAuthValidationResponseSchema,
  mediaSchema,
  pageSchema,
  postSchema,
  postWriteBaseSchema,
  searchResultSchema,
  settingsSchema,
  stripDateTimeFormats,
  tagSchema,
  updatePostFieldsSchema,
  wordPressErrorSchema,
  zodFromJsonSchema,
  zodSchemasFromDescription,
} from 'fluent-wp-client/zod';
export type {
  AbilityActionOptions,
  ActionClientResolver,
  ActionResponseMapper,
  CreatePostActionConfig,
  CreatePostActionOptions,
  CreatePostInput,
  CreateTermActionConfig,
  CreateTermActionOptions,
  CreateTermInput,
  CreateUserActionConfig,
  CreateUserActionOptions,
  CreateUserInput,
  DeleteAbilityActionConfig,
  DeletePostActionConfig,
  DeletePostActionOptions,
  DeletePostInput,
  DeletePostResult,
  DeleteTermActionConfig,
  DeleteTermActionOptions,
  DeleteTermInput,
  DeleteTermResult,
  DeleteUserActionConfig,
  DeleteUserActionOptions,
  DeleteUserInput,
  DeleteUserResult,
  ExecuteAbilityOptions,
  ExecuteCreateConfig,
  ExecuteCreateOptions,
  ExecuteCreateTermConfig,
  ExecuteCreateTermOptions,
  ExecuteCreateUserConfig,
  ExecuteCreateUserOptions,
  ExecuteDeleteAbilityConfig,
  ExecuteDeleteAbilityOptions,
  ExecuteDeleteConfig,
  ExecuteDeleteOptions,
  ExecuteDeleteTermConfig,
  ExecuteDeleteTermOptions,
  ExecuteDeleteUserConfig,
  ExecuteDeleteUserOptions,
  ExecuteGetAbilityConfig,
  ExecuteGetAbilityOptions,
  ExecuteRunAbilityConfig,
  ExecuteRunAbilityOptions,
  ExecuteUpdateConfig,
  ExecuteUpdateOptions,
  ExecuteUpdateTermConfig,
  ExecuteUpdateTermOptions,
  ExecuteUpdateUserConfig,
  ExecuteUpdateUserOptions,
  GetAbilityActionConfig,
  ResolvableActionClient,
  RunAbilityActionConfig,
  UpdatePostActionConfig,
  UpdatePostActionOptions,
  UpdatePostInput,
  UpdateTermActionConfig,
  UpdateTermActionOptions,
  UpdateTermInput,
  UpdateUserActionConfig,
  UpdateUserActionOptions,
  UpdateUserInput,
  WpCacheInvalidateInput,
} from './actions';
// Export predefined server actions
export {
  createCreatePostAction,
  createCreateTermAction,
  createCreateUserAction,
  createDeleteAbilityAction,
  createDeletePostAction,
  createDeleteTermAction,
  createDeleteUserAction,
  createGetAbilityAction,
  createPostInputSchema,
  createRunAbilityAction,
  createTermInputSchema,
  createUpdatePostAction,
  createUpdateTermAction,
  createUpdateUserAction,
  createUserInputSchema,
  createWpCacheInvalidateAction,
  deleteAbilityInputSchema,
  deletePostInputSchema,
  deleteTermInputSchema,
  deleteUserInputSchema,
  getAbilityInputSchema,
  runAbilityInputSchema,
  updatePostInputSchema,
  updateTermInputSchema,
  updateUserInputSchema,
  wpCacheInvalidateInputSchema,
} from './actions';
export type {
  CategoryFilter,
  ContentFilter,
  MediaFilter,
  PageFilter,
  PostFilter,
  TagFilter,
  TermFilter,
  UserFilter,
  WordPressContentLoaderOptions,
  WordPressContentStaticLoaderOptions,
  WordPressEmbedMode,
  WordPressEntryMappingOptions,
  WordPressLiveContentLoaderOptions,
  WordPressLoaderEntryMapper,
  WordPressTermLoaderOptions,
  WordPressTermStaticLoaderOptions,
} from './loaders';
// Export live loaders (for defineLiveCollection - runtime fetching)
// Export static loaders (for defineCollection - build-time only)
export {
  wordPressCategoryLoader,
  wordPressCategoryStaticLoader,
  wordPressContentLoader,
  wordPressContentStaticLoader,
  wordPressMediaLoader,
  wordPressMediaStaticLoader,
  wordPressPageLoader,
  wordPressPageStaticLoader,
  wordPressPostLoader,
  wordPressPostStaticLoader,
  wordPressTagLoader,
  wordPressTagStaticLoader,
  wordPressTermLoader,
  wordPressTermStaticLoader,
  wordPressUserLoader,
  wordPressUserStaticLoader,
} from './loaders';
export type {
  WordPressAuthBridge,
  WordPressAuthBridgeConfig,
  WordPressAuthSession,
  WordPressLoginAction,
  WordPressLoginActionPayload,
  WordPressLoginActionResult,
  WordPressLoginInput,
} from './server';
// Export server auth bridge helpers
export {
  createWordPressAuthBridge,
  wordPressLoginInputSchema,
} from './server';

// Components are imported directly via:
// import WPImage from 'wp-astrojs-integration/components/WPImage.astro';
// import WPContent from 'wp-astrojs-integration/components/WPContent.astro';
